/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(demod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a0e3ec99689bb55b6b8dcc560a05bd07)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lora/demod.h>
// pydoc.h is automatically generated in the build directory
#include <demod_pydoc.h>

void bind_demod(py::module& m)
{

    using demod    = ::gr::lora::demod;


    py::class_<demod, gr::block, gr::basic_block,
        std::shared_ptr<demod>>(m, "demod", D(demod))

        .def(py::init(&demod::make),
           py::arg("spreading_factor"),
           py::arg("low_data_rate"),
           py::arg("beta"),
           py::arg("fft_factor"),
           D(demod,make)
        )
        



        ;

    py::enum_<::gr::lora::demod_state_t>(m,"demod_state_t")
        .value("S_RESET", ::gr::lora::S_RESET) // 0
        .value("S_PREFILL", ::gr::lora::S_PREFILL) // 1
        .value("S_DETECT_PREAMBLE", ::gr::lora::S_DETECT_PREAMBLE) // 2
        .value("S_SFD_SYNC", ::gr::lora::S_SFD_SYNC) // 3
        .value("S_READ_HEADER", ::gr::lora::S_READ_HEADER) // 4
        .value("S_READ_PAYLOAD", ::gr::lora::S_READ_PAYLOAD) // 5
        .value("S_OUT", ::gr::lora::S_OUT) // 6
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::lora::demod_state_t>();



}








